--- 
extends: existence
message: "Avoid generic link text like '%s'. Use descriptive link text instead."
description: >
  Descriptive link text improves accessibility and SEO by clearly indicating
  where the link leads, rather than using vague terms.
level: warning
raw:
  - '(?i)\[(?:click here|here)\]\([^)]*\)'
